In [1]:
import pandas as pd
import geopandas as gpd

from pathlib import Path

In [2]:
path_camels = Path('/mnt/c/Datasets/CAMELS-ES')

In [11]:
version= 'v110'
camels = gpd.read_file(path_camels / version / 'shapefiles/camelses/camelses_basin_shapes.shp').set_index('gauge_id')
camels.index = [int(x.split('_')[1]) for x in camels.index]
camels.index.name = 'COD_HIDRO'
camels.head()

                                                    geometry
COD_HIDRO
1080       POLYGON ((-1.93135 43.01457, -1.93134 43.01528...
1103       POLYGON ((-2.4218 43.2358, -2.42181 43.23439, ...
1105       POLYGON ((-1.90497 43.25597, -1.90499 43.25527...
1106       MULTIPOLYGON (((-1.67921 43.31065, -1.67926 43...
1109       POLYGON ((-2.23924 43.27136, -2.23925 43.27066...

In [33]:
anuario.columns

Index(['NOM_ANUARIO', 'RIO', 'REGIMEN_RIO', 'COD_SAIH', 'COD_DMA',
       'COD_MASA_AGUA', 'FOTOGRAFIA', 'PLANO', 'SECCION',
       'ORGANISMO_CUENCA_VISOR', 'COD_SITUACION_ESTACION',
       'SITUACION_ESTACION', 'ESTADO', 'ANO_INICIO_MEDIDAS', 'ANO_FIN_MEDIDAS',
       'COD_SAICA', 'COORD_UTMX_H30_ETRS89', 'COORD_UTMY_H30_ETRS89', 'COTA_Z',
       'CUENCA_RECEP', 'CUENCA_TOTAL', 'NUM_CUENCA', 'HOJA_1_50000',
       'SISTEMA_EXPLO', 'ESCALA_RC', 'LONG_RC', 'ANCH_RC', 'CASETA_RC',
       'PASARELA_RC', 'PROPIETARIO', 'SENSOR_1', 'TIPO_CASETA_RC',
       'TIPO_ESC_RC', 'TIPO_ESTACION', 'TRANSM_1', 'VERTEDERO_RC',
       'TIPO_VERT_RC', 'TERMINO_MUNICIPAL', 'PROVINCIA', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45'],
      dtype='str')

In [42]:
anuario = pd.read_csv(
    path_camels / 'raw' / '2020-2021' / 'estaciones' / 'Situac 4_Rio.csv',
    sep=';',
    index_col='COD_HIDRO', 
    encoding='latin-1'
    )

mask_regimen = anuario.REGIMEN_RIO.str.lower() == 'natural'
mask_serie = (anuario.ANO_FIN_MEDIDAS.isnull()) |  (anuario.ANO_FIN_MEDIDAS > 1995)
anuario = anuario[mask_regimen & mask_serie]

print(len(anuario))
anuario.head()

369

,NOM_ANUARIO,RIO,REGIMEN_RIO,COD_SAIH,COD_DMA,COD_MASA_AGUA,FOTOGRAFIA,PLANO,SECCION,ORGANISMO_CUENCA_VISOR,...,VERTEDERO_RC,TIPO_VERT_RC,TERMINO_MUNICIPAL,PROVINCIA,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
COD_HIDRO,,,,,,,,,,,,,,,,,,,,,
1106,ENDARLAZA,Bidasoa,NATURAL,A140,ESBI05N,ES017MSPFES010MAR002420,FR1106.jpg,PR1106.jpg,SR1106.jpg,C.H. CANTÁBRICO,...,NaN,NaN,Irún,Guipúzcoa,NaN,NaN,NaN,NaN,NaN,NaN
1107,OYARZUN,Oyarzun,NATURAL,A801,NaN,ES017MSPFES111R014010,FR1107.jpg,PR1107.jpg,SR1107.jpg,C.H. CANTÁBRICO,...,NaN,NaN,Oyartzun,Guipúzcoa,NaN,NaN,NaN,NaN,NaN,NaN
1141,BERRIATÚA,Artibay,NATURAL,A850,NaN,ES017MSPFES111R044010,FR1141.jpg,PR1141.jpg,SR1141.jpg,C.H. CANTÁBRICO,...,NaN,NaN,Berriatúa,Vizcaya,NaN,NaN,NaN,NaN,NaN,NaN
1201,ASÓN EN RAMALES,ASÓN,NATURAL,A141,NaN,ES078MAR000050,FR1201.jpg,N.D.jpg,N.D.jpg,C.H. CANTÁBRICO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202,CARRANZA EN PONDRÁ,CARRANZA,NATURAL,A143,NaN,ES078MAR000050,FR1202.jpg,N.D.jpg,N.D.jpg,C.H. CANTÁBRICO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
len(camels.index.intersection(anuario.index))

137